# Permalinks
permalink:        pretty

# Site settings
title:            Richard Osterloh
description:      Richard Osterloh - Github page
url:              rosterloh.github.io
paginate:         10
baseurl:          /
google_analytics: UA-49296776-1

author:
  name:               Richard Osterloh
  email:              richard.osterloh@gmail.com
  twitter_username:   richard84
  # facebook_username: richard.osterloh
  github_username:    rosterloh
  linkedin_username:  richardosterloh

# Build settings
#destination: _site
#permalink: /:year/:title/
#markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  syntax_highlighter: rouge

gems: [jekyll-paginate, jekyll-gist]
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
